version: '3.8'

services:

  autoheal:
    image: willfarrell/autoheal:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    image: api
    build: ./api
    restart: always
    labels:
      - autoheal=true
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - 80:80
    environment:
      MONGODB_URL:
        "mongodb://\
        ${MONGO_ROOT_USERNAME:-root}:\
        ${MONGO_ROOT_PASSWORD:-changeme}@\
        ${MONGO_HOST:-mongo}:\
        ${MONGO_PORT:-27017}/"
    healthcheck:
      test: curl --fail http://localhost/api/health || exit 1
      interval: 10s
      timeout: 1s
      retries: 3
      start_period: 10s

  upgrader:
    image: upgrader
    build: ./upgrader
    restart: always
    environment:
      MONGODB_URL:
        "mongodb://\
        ${MONGO_ROOT_USERNAME:-root}:\
        ${MONGO_ROOT_PASSWORD:-changeme}@\
        ${MONGO_HOST:-mongo}:\
        ${MONGO_PORT:-27017}/"
      API_KEY: ${API_KEY}
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo
    labels:
      - autoheal=true
    restart: always
    ports:
      - ${MONGO_PORT:-27017}:${MONGO_PORT:-27017}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-changeme}
    volumes:
      - mongodb:/data/db
    healthcheck:
      test: 
        - CMD
        - mongosh
        - --eval
        - db.runCommand('ping').ok
        - localhost:27017/test
        - --quiet
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 10s

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL:
        "mongodb://\
        ${MONGO_ROOT_USERNAME:-root}:\
        ${MONGO_ROOT_PASSWORD:-changeme}@\
        ${MONGO_HOST:-mongo}:\
        ${MONGO_PORT:-27017}/"
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD:-pass}
    depends_on:
      mongo:
        condition: service_healthy

volumes:
  mongodb: