version: '3.1'

services:

  api:
    image: api
    build: ./api
    restart: always
    depends_on:
      - upgrader
    ports:
      - 80:8000
    environment:
      MONGODB_URL:
        "mongodb://\
        ${MONGO_ROOT_USERNAME:-root}:\
        ${MONGO_ROOT_PASSWORD:-changeme}@\
        ${MONGO_HOST:-mongo}:\
        ${MONGO_PORT:-27017}/"

  upgrader:
    image: upgrader
    build: ./upgrader
    restart: always
    environment:
      MONGODB_URL:
        "mongodb://\
        ${MONGO_ROOT_USERNAME:-root}:\
        ${MONGO_ROOT_PASSWORD:-changeme}@\
        ${MONGO_HOST:-mongo}:\
        ${MONGO_PORT:-27017}/"
      API_KEY: ${API_KEY}
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - ${MONGO_PORT:-27017}:${MONGO_PORT:-27017}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-changeme}
    volumes:
      - mongodb:/data/db
    
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL:
        "mongodb://\
        ${MONGO_ROOT_USERNAME:-root}:\
        ${MONGO_ROOT_PASSWORD:-changeme}@\
        ${MONGO_HOST:-mongo}:\
        ${MONGO_PORT:-27017}/"
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME:-admin}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD:-pass}
    depends_on:
      - mongo

volumes:
  mongodb: